<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class OrdenSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $ordenes = [
            // Órdenes del mes pasado
            [
                'usuario_id' => 2,
                'estado' => 'entregado',
                'tipo_servicio' => 'domicilio',
                'subtotal' => 45.50,
                'impuestos' => 7.28,
                'total' => 52.78,
                'direccion_entrega' => 'Avenida 2 #456',
                'telefono_contacto' => '+1 555-0102',
                'fecha_orden' => '2024-09-05 12:30:00',
                'fecha_pendiente' => '2024-09-05 12:30:00',
                'fecha_entregado' => '2024-09-05 13:30:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'usuario_id' => 3,
                'estado' => 'entregado',
                'tipo_servicio' => 'recoger',
                'subtotal' => 32.00,
                'impuestos' => 5.12,
                'total' => 37.12,
                'direccion_entrega' => null,
                'telefono_contacto' => '+1 555-0103',
                'fecha_orden' => '2024-09-08 14:15:00',
                'fecha_pendiente' => '2024-09-08 14:15:00',
                'fecha_entregado' => '2024-09-08 15:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'usuario_id' => 4,
                'estado' => 'entregado',
                'tipo_servicio' => 'domicilio',
                'subtotal' => 67.80,
                'impuestos' => 10.85,
                'total' => 78.65,
                'direccion_entrega' => 'Calle 4 #321',
                'telefono_contacto' => '+1 555-0104',
                'fecha_orden' => '2024-09-12 18:45:00',
                'fecha_pendiente' => '2024-09-12 18:45:00',
                'fecha_entregado' => '2024-09-12 19:30:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'usuario_id' => 5,
                'estado' => 'entregado',
                'tipo_servicio' => 'recoger',
                'subtotal' => 28.50,
                'impuestos' => 4.56,
                'total' => 33.06,
                'direccion_entrega' => null,
                'telefono_contacto' => '+1 555-0105',
                'fecha_orden' => '2024-09-15 11:20:00',
                'fecha_pendiente' => '2024-09-15 11:20:00',
                'fecha_entregado' => '2024-09-15 12:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'usuario_id' => 6,
                'estado' => 'entregado',
                'tipo_servicio' => 'domicilio',
                'subtotal' => 54.20,
                'impuestos' => 8.67,
                'total' => 62.87,
                'direccion_entrega' => 'Boulevard 6 #987',
                'telefono_contacto' => '+1 555-0106',
                'fecha_orden' => '2024-09-18 19:30:00',
                'fecha_pendiente' => '2024-09-18 19:30:00',
                'fecha_entregado' => '2024-09-18 20:15:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // Órdenes de este mes
            [
                'usuario_id' => 2,
                'estado' => 'entregado',
                'tipo_servicio' => 'domicilio',
                'subtotal' => 41.00,
                'impuestos' => 6.56,
                'total' => 47.56,
                'direccion_entrega' => 'Avenida 2 #456',
                'telefono_contacto' => '+1 555-0102',
                'fecha_orden' => '2024-10-02 13:00:00',
                'fecha_pendiente' => '2024-10-02 13:00:00',
                'fecha_entregado' => '2024-10-02 13:45:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'usuario_id' => 4,
                'estado' => 'entregado',
                'tipo_servicio' => 'recoger',
                'subtotal' => 38.90,
                'impuestos' => 6.22,
                'total' => 45.12,
                'direccion_entrega' => null,
                'telefono_contacto' => '+1 555-0104',
                'fecha_orden' => '2024-10-03 17:15:00',
                'fecha_pendiente' => '2024-10-03 17:15:00',
                'fecha_entregado' => '2024-10-03 18:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'usuario_id' => 5,
                'estado' => 'entregado',
                'tipo_servicio' => 'domicilio',
                'subtotal' => 72.50,
                'impuestos' => 11.60,
                'total' => 84.10,
                'direccion_entrega' => 'Avenida 5 #654',
                'telefono_contacto' => '+1 555-0105',
                'fecha_orden' => '2024-10-04 20:00:00',
                'fecha_pendiente' => '2024-10-04 20:00:00',
                'fecha_entregado' => '2024-10-04 20:45:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'usuario_id' => 6,
                'estado' => 'entregado',
                'tipo_servicio' => 'recoger',
                'subtotal' => 29.80,
                'impuestos' => 4.77,
                'total' => 34.57,
                'direccion_entrega' => null,
                'telefono_contacto' => '+1 555-0106',
                'fecha_orden' => '2024-10-05 12:45:00',
                'fecha_pendiente' => '2024-10-05 12:45:00',
                'fecha_entregado' => '2024-10-05 13:30:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'usuario_id' => 7,
                'estado' => 'entregado',
                'tipo_servicio' => 'domicilio',
                'subtotal' => 55.60,
                'impuestos' => 8.90,
                'total' => 64.50,
                'direccion_entrega' => 'Calle 7 #159',
                'telefono_contacto' => '+1 555-0107',
                'fecha_orden' => '2024-10-06 15:30:00',
                'fecha_pendiente' => '2024-10-06 15:30:00',
                'fecha_entregado' => '2024-10-06 16:15:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // Órdenes de hoy
            [
                'usuario_id' => 2,
                'estado' => 'entregado',
                'tipo_servicio' => 'domicilio',
                'subtotal' => 48.90,
                'impuestos' => 7.82,
                'total' => 56.72,
                'direccion_entrega' => 'Avenida 2 #456',
                'telefono_contacto' => '+1 555-0102',
                'fecha_orden' => now(),
                'fecha_pendiente' => now(),
                'fecha_entregado' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'usuario_id' => 8,
                'estado' => 'listo',
                'tipo_servicio' => 'recoger',
                'subtotal' => 35.00,
                'impuestos' => 5.60,
                'total' => 40.60,
                'direccion_entrega' => null,
                'telefono_contacto' => '+1 555-0108',
                'fecha_orden' => now(),
                'fecha_pendiente' => now(),
                'fecha_listo' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'usuario_id' => 9,
                'estado' => 'preparando',
                'tipo_servicio' => 'domicilio',
                'subtotal' => 62.30,
                'impuestos' => 9.97,
                'total' => 72.27,
                'direccion_entrega' => 'Boulevard 9 #951',
                'telefono_contacto' => '+1 555-0109',
                'fecha_orden' => now(),
                'fecha_pendiente' => now(),
                'fecha_preparando' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'usuario_id' => 10,
                'estado' => 'pendiente',
                'tipo_servicio' => 'recoger',
                'subtotal' => 27.50,
                'impuestos' => 4.40,
                'total' => 31.90,
                'direccion_entrega' => null,
                'telefono_contacto' => '+1 555-0110',
                'fecha_orden' => now(),
                'fecha_pendiente' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($ordenes as $orden) {
            DB::table('ordenes')->insertOrIgnore($orden);
        }
    }
}
